var shorts = [" ain't "," are'nt "," are'nt "," aren t "," aren't "," aren't "," arent "," arn t "," cannot "," can't "," can't "," colour "," couldn't "," didn't "," didnt "," doesn't "," doesnt "," don't "," don't "," dont "," down load "," hadn't "," hasn't "," haven't "," he'd "," hed "," he'll "," he's  "," how'd "," how's "," hows "," I'd "," I'll "," I'll "," I m "," I'm "," I'm "," is'nt "," isn t "," isn't "," isn't "," isnt "," its a "," it s "," it's "," it's "," I ve "," I've "," I've "," ive "," l a "," let's  "," loebner price "," name's "," noi "," ohh "," o k "," practice "," p s "," realy "," reductionalism "," remeber "," r u "," ru "," she d "," she'd "," shed "," she s "," she's "," shes "," shouldn't "," shouldn't "," shouldnt "," that's "," thats "," there s "," there's "," theres "," they re "," they're "," u r "," ur "," ur "," u "," u "," waht "," wallance "," wanna "," wasn t "," wasn't "," wasnt "," wellit "," welli "," we ll "," we'll "," weren t "," weren't "," werent "," we re "," we're "," we ve "," we've "," what s "," what's "," what's "," whats "," where s "," where's "," who s "," who's "," whos "," won t "," won't "," won't "," wont "," wouldn t "," wouldn't "," wouldn't "," wouldnt "," yeah "," yep "," yesit "," yesi "," yha "," you'd "," you ll "," you'll "," you re "," you're "," youre "," you r "," you ve "," you've "," you've "] ;

var longs = [" is not ","are not ","are not ","are not ","are not ","are not ","are not ","are not ","can not ","can not ","can not ","color ","could not ","did not ","did not ","does not ","does not ","do not ","do not ","do not ","download ","had not ","has not ","have not ","he would ","he would ","he will ","he is  ","how did ","how is ","how is ","I would ","I will ","I will ","I am ","I am ","I am ","is not ","is not ","is not ","is not ","is not ","it is a ","it is ","it is ","it is ","I have ","I have ","I have ","I have ","la ","let us  ","loebner prize ","name is ","yes I ","oh ","ok ","practise ","ps ","really ","reductionism ","remember ","are you ","are you ","she would ","she would ","she would ","she is ","she is ","she is ","should not ","should not ","should not ","that is ","that is ","there is ","there is ","there is ","they are ","they are ","you are ","your ","your ","you ","you ","what ","wallace ","want to ","was not ","was not ","was not ","well it ","well I ","we will ","we will ","were not ","were not ","were not ","we are ","we are ","we have ","we have ","what is ","what is ","what is ","what is ","where is ","where is ","who is ","who is ","who is ","will not ","will not ","will not ","will not ","would not ","would not ","would not ","would not ","yes ","yes ","yes it ","yes I ","yes ","you would ","you will ","you will ","you are ","you are ","you are ","you are ","you have ","you have ","you have "];



function findReplace(matchList, switchList, text){
	for(var i=0; i<matchList.length;i++){
		var re = new RegExp(matchList[i], "ig")
		text = text.replace(re, switchList[i]);
		//document.write(i+". "+matchList[i]+"=>"+switchList[i]+"<br />");
	}
	console.log(text)
	return text;
} 